org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
## Gradle caching is bad with NeoForge systems so ALWAYS keep it disabled even if you know what you are doing.
org.gradle.configuration-cache=false
org.gradle.unsafe.configuration-cache=false
org.gradle.caching=false
## Caching in Gradle is fragile and can cause a LOT of issues if not used correctly.
## Keep it disabled if you DON'T KNOW WHAT you're doing.
net.neoforged.gradle.caching.enabled=false
# NeoForge and Minecraft data
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.250
# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

mod_id=create_realistic_railroad_crossings
mod_name=Create: Realistic Railroad Crossings
mod_license=GNU GPL v2.0
mod_version=1.0.0
mod_group_id=com.create_level_crossings_dev.create_realistic_railroad_crossings
